### PR TITLE
Guest view

### PR DESCRIPTION
**Pull request by vijayrahul25**
Current system don't allow guest to view spoiler content, we have requirement where we think that spoiler content should be allowed to viewed by any user.

Steps to reproduce: 

Go to website and do not log
find a topic containing spoiler
click on eye icon to display spoiler content
-> eye icon changes but content is not displayed

### CODE REVIEW

**Comment by vijayrahul25** [comment]
Hi @julianlam @barisusakli 
Can you please review this request.

Thanks
Rahul
Ubisoft

**Review by julianlam — APPROVED** [review]
Not sure why the spoiler plugin didn't allow guests to view spoilers... To prevent indexing maybe?

**Comment by barisusakli** [comment]
`controller.getSpoilerContent` function doesn't seem to have any privilege checks so anyone can read private posts. Privilege check needs to be added.

**Comment by barisusakli** [comment]
Fixed in https://github.com/NicolasSiver/nodebb-plugin-ns-spoiler/pull/36

**Pull request closed without merging**
